[tool.black]
line-length = 88
target-version = ['py310']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
python_version = "3.10"
warn_no_return = true
warn_unreachable = true
warn_incomplete_stub = true
warn_unused_configs = true

[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
skip_gitignore = true
extra_standard_library = ["typing_extensions"]
skip = [
]
