repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: src
        args: [--install-types, --non-interactive]
        additional_dependencies:
          - pydantic==2.10.2
