repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive]
        additional_dependencies:
          - pydantic
