[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_no_return = true
warn_unreachable = true
warn_incomplete_stub = true
warn_unused_configs = true
plugins = [
    "pydantic.mypy"
]

exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
]
