repos:
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-simplify
          - flake8-class-attributes-order
          - flake8-comprehensions
          - flake8-use-fstring
          - flake8-functions-names
          - pep8-naming
          - yesqa
          - flake8-absolute-import
          - flake8-implicit-str-concat
          - flake8-black
          - flake8-isort
