repos:
  - repo: https://github.com/myint/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args:
          - "--remove-all-unused-imports"
          - "--in-place"
          - "--ignore-init-module-imports"
